### ISSUE TITLE
Design Landing Page of web app

### ISSUE THREAD

**Issue by LeviButcher** [studentsXbooks/studentsXbooks-app#21]

**Comment by GandoraGalaxy** [comment]
![Mock_Landing_Page](https://user-images.githubusercontent.com/31375737/65437088-2b9bd300-ddf1-11e9-953d-8851cf60b968.PNG)
![New_Mock_Landing_Page](https://user-images.githubusercontent.com/31375737/65437090-2b9bd300-ddf1-11e9-8a0c-8ed2ee42106b.PNG)
