### ISSUE TITLE
Complete overhaul on site design

### ISSUE THREAD

**Issue by LeviButcher** [studentsXbooks/studentsXbooks-app#58]

**Comment by jeremii** [comment]
### Universal
- [ ] logo in nav bar
- [ ] quasi-responsive design

### Home
- [ ] logo above search bar
- [ ] Rounded search bar
- [ ] search bar layered over photo
- [ ] dark overlay over photo
- [ ] "Find your textbooks!" header above search bar
- [ ] "background image" property of book shelf in css
- [ ] bookshelf image get rid of outlet
- [ ] maybe retake retake photo
- [ ] colors - design language of colors
- [ ] placeholder text for search

### Register
- [ ] layout needs to match design files
- [ ] rounded textboxes

### Login
- [ ] add copy
- [ ] login text boxes to the right side

### Search listing
- [ ] Search bar spans screen
- [ ] condition checkbox doubles as legend with colors 
- [ ] price range under conditions
- [ ] overhaul

### Listing details
- [ ] minuscule changes

### New Listing (Sell)
- [ ] Vertically compress text boxes
- [ ] background color light gray

### Sell
- [ ] do not display search bar

### About
- [ ] logo
- [ ] color scheme
- [ ] header size

### Help
- [ ] plus icon on FAQ item
- [ ] plus icon opens content (material "expander")
- [ ] "Dev contacts/helpful links" align to left
- [ ] mailto link on email

**Comment by jeremii** [comment]
### _Due: Wednesday, December 4_


### @GandoraGalaxy 
**Search listing**
- [ ] Condition checkbox doubles as legend with colors 

### @BradyStarcher 
**Search listing**
- [ ] Align min & max price fields with submit button

**Help**
- [ ] "Dev contacts/helpful links" align to left

### @jeremii 
**Help**
- [ ] Plus icon opens FAQ content (material "expander")

**Comment by LeviButcher** [comment]
Closed with #55
