### ISSUE TITLE
Create Listing: Needs to clearly display units for price

### ISSUE THREAD

**Issue by LeviButcher** [studentsXbooks/studentsXbooks-app#84]
Change the input to show a '$' and a decimal place.

I would love it to look like this. https://codepen.io/559wade/pen/LRzEjj 
But without jquery.

However, doing a simple solution that is clear is fine.
Please post an image of the input during the merge request.

**Comment by GandoraGalaxy** [comment]
Added $ and example to the placeholder text as well as a disclaimer in the title of the price field.
